### ISSUE TITLE
Extracting just individual files

### ISSUE THREAD

**Issue by breadbyte** [Droppers/SingleFileExtractor#2]
Hello!

First of all, great library!

I was wondering, is there a way or an option to be able to extract just the individual files themselves?
I am currently invoking `GetStreamForFileEntry` from `BundleExtractor` manually using reflection as a workaround.

**Comment by Droppers** [comment]
You mean that instead of extracting all files, you want to extract a specific file, e.g. by name?

**Comment by breadbyte** [comment]
Yes.

**Comment by Droppers** [comment]
You can now extract a specific file:

```cs
var manifest = new ExecutableReader().Read("Application.exe");
var file = manifest.Files.Single(x => x.RelativePath == "Example.dll");
file.Extract("ExtractedExample.dll"); // or file.AsStream()
```

**Comment by breadbyte** [comment]
Awesome!
Is it possible to expose the file as a stream?

**Comment by Droppers** [comment]
Yes, just use `file.AsStream()`

**Comment by breadbyte** [comment]
`FileEntry.AsStream()` doesn't seem to exist.

**Comment by wisemoth** [comment]
I'd love to be able to access a `FileEntry` as a stream too.

**Comment by Droppers** [comment]
I have changed the API in version 2. This is know possible, see the readme for more information.
