### ISSUE TITLE
netstandard2.0 build

### ISSUE THREAD

**Issue by Shockah** [Droppers/SingleFileExtractor#7]
Any chance for a `netstandard2.0` build? I'd like to use this package as part of my custom MSBuild task, but these have to be `netstandard2.0`, which means I can't use the Core package as-is.

**Comment by Droppers** [comment]
I will look into this 👍🏻

**Comment by Droppers** [comment]
Version 2.2.0 targets netstandard2.0, let me know if it works as expected!

**Comment by Shockah** [comment]
Yep, I've implemented it into my NuGet package and it works perfectly! Thank you.
