### ISSUE TITLE
Cannot extract from a file larger than int.MaxValue

### ISSUE THREAD

**Issue by jpopebiomerieux** [Droppers/SingleFileExtractor#8]
My very large file can no longer be extracted after pushing its size beyond int.MaxValue bytes. Some information is lost when a long is casted to an int.
https://github.com/Droppers/SingleFileExtractor/blob/eadc323085209acee75dd60964f409dde85d76a6/src/SingleFileExtractor.Core/Helpers/BinaryKmpSearch.cs#L10

**Comment by Droppers** [comment]
Thank you for reporting. Fixed in version 2.1.1, it now uses long instead of int.
